### ISSUE TITLE
App picker view

### ISSUE THREAD

**Issue by mbelousov** [healtex/texscrubber#10]
Should have two buttons: "De-identification" and "Visualisation"

**Comment by RichJackson** [comment]
Can You create a branch called user_interface so I can create a pull request?

**Comment by mbelousov** [comment]
@RichJackson, I have granted admin permissions to DEID group for this repository, so now you should be able to create branches. Going back to Git flow branching model discussed during a hackathon, please keep in mind naming conventions, e.g. feature/user-interface for UI developments.
