### ISSUE TITLE
Integrate feature/gui with feature/ner-integration

### ISSUE THREAD

**Issue by dehghana** [healtex/texscrubber#29]

**Comment by hkkenneth** [comment]
Sidenote:

Re @mbelousov 's question about keeping track of process, to get the number of files read / write, can use getReadCount() or getWriteCount() etc.
http://docs.spring.io/spring-batch/apidocs/org/springframework/batch/core/StepExecution.html

Or if it has to be more real-time, can use http://docs.spring.io/spring-batch/2.2.x/apidocs/org/springframework/batch/core/ItemReadListener.html ?
