### ISSUE TITLE
OutputWriter implementation

### ISSUE THREAD

**Issue by mbelousov** [healtex/texscrubber#9]
Output resulting scrubbed file

**Comment by owendw1** [comment]
Assuming OutputWriter is still meant to receive a GATEDocument, is it then supposed write certain attributes of the document to screen/file for summary purposes?

**Comment by mbelousov** [comment]
See #20

**Comment by mbelousov** [comment]
Need to integrate scrubber processor (See #7):
- In AnnotatedDocument.java (https://github.com/healtex/texscrubber/blob/feature/ner-integration/src/main/java/org/healtex/model/AnnotatedDocument.java) add method getScrubbedText() to replace all annotations (using scrubberprocessor that takes gate.Document as input and annotations [that should be "deid"] ) 
- In DeidentifiedDocumentWriter.java (https://github.com/healtex/texscrubber/blob/feature/ner-integration/src/main/java/org/healtex/batch/writer/DeidentifiedDocumentWriter.java) create a new .txt file in outputPath directory that would contain scrubbed text

You can find scrubber processor here: https://github.com/healtex/texscrubber/tree/feature/ScrubberProcessor
